AWSTemplateFormatVersion: 2010-09-09
Description: Master stack

Metadata:
  AWS::CloudFormation::InterFace:
    ParameterGroups:
      - Label:
          default: SES Configration
        Parameters:
          - SESTemplateURL
          - Email

      - Label:
          default: API Gateway Conditions
        Parameters:
          - RestAPITemplateURL
          - APIGatewayTemplateURL

      - Label:
          default: StepFunction Conditions
        Parameters:
          - StepFunctionTemplateURL

      - Label:
          default: Lambda Conditions
        Parameters:
          - LambdaApprovalTemplateURL
          - LambdaSendEmailTemplateURL
          - LambdaAccountCreationTemplateURL
          - support_mail_address
          - approver_mail_address
          - DEBUG_MODE
    
    ParameterLabels:
      SESTemplateURL:
        default: SESTemplateURL
      
      Email:
        default: Email        

      RestAPITemplateURL:
        default: RestAPITemplateURL

      APIGatewayTemplateURL:
        default: APIGatewayTemplateURL
        
      StepFunctionTemplateURL:
        default: StepFunctionTemplateURL

      LambdaApprovalTemplateURL:
        default: LambdaApprovalTemplateURL

      LambdaSendEmailTemplateURL:
        default: LambdaSendEmailTemplateURL

      LambdaAccountCreationTemplateURL:
        default: LambdaAccountCreationTemplateURL

      support_mail_address:
        default: supportmailaddress

      approver_mail_address:
        default: approvermailaddress

      DEBUG_MODE:
        default: Areyougoingtodeploytotestingsite

Parameters:
  Email:
    Type: String
    AllowedPattern: "^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$"
    ConstraintDescription: Must be a valid email address.

  supportmailaddress:
    Type: String
    Default: aws_tec@ashisuto.co.jp

  approvermailaddress:
    Type: String
    Default: awssp_ship@ashisuto.co.jp

  Areyougoingtodeploytotestingsite:
    Type: String
    AllowedValues: 
      - true
      - false

  RestAPITemplateURL:
    Type: String
    Default: https://cfn-template-tnunomura.s3.ap-northeast-3.amazonaws.com/RestAPI.yml
  
  APIGatewayTemplateURL:
    Type: String
    Default: https://cfn-template-tnunomura.s3.ap-northeast-3.amazonaws.com/APIGateway.yml

  SESTemplateURL:
    Type: String
    Default: https://cfn-template-tnunomura.s3.ap-northeast-3.amazonaws.com/SES.yml

  StepFunctionTemplateURL:
    Type: String
    Default: https://cfn-template-tnunomura.s3.ap-northeast-3.amazonaws.com/StepFunction.yml

  LambdaApprovalTemplateURL:
    Type: String
    Default: https://cfn-template-tnunomura.s3.ap-northeast-3.amazonaws.com/LambdaApprovalFunction.yml

  LambdaSendEmailTemplateURL:
    Type: String
    Default: https://cfn-template-tnunomura.s3.ap-northeast-3.amazonaws.com/LambdaHumanApprovalSendEmailFunction.yml

  LambdaAccountCreationTemplateURL:
    Type: String
    Default: https://cfn-template-tnunomura.s3.ap-northeast-3.amazonaws.com/LambdaAccountCreationFunction.yml

Resources:

#Rest API Create
  RestAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref RestAPITemplateURL

#API Gateway Create
  APIGateway:
    DependsOn:
      - StepFunction
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref APIGatewayTemplateURL
      Parameters:
        LambdaApprovalFunction: !GetAtt LambdaApproval.Outputs.LambdaApproval
        RestAPI: !GetAtt RestAPI.Outputs.RestAPI
        ExecutionResource: !GetAtt RestAPI.Outputs.ExecutionResource
        StartStepFunctionResource: !GetAtt  RestAPI.Outputs.StartStepFunctionResource
        StepFunction: !GetAtt StepFunction.Outputs.StateMachineHumanApproval

#SES Create
  SES:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref SESTemplateURL
      Parameters:
        Email: !Sub '${Email}'

#Step Function Create
  StepFunction:
    DependsOn:
      - LambdaSendEmail
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref StepFunctionTemplateURL
      Parameters:
        LambdaAccountCreationFunction: !GetAtt LambdaAccountCreation.Outputs.LambdaAccountCreation 
        LambdaHumanApprovalSendEmailFunction: !GetAtt LambdaSendEmail.Outputs.LambdaSendEmail
        RestAPI: !GetAtt RestAPI.Outputs.RestAPI

#Lambda Approval Create
  LambdaApproval:
    DependsOn:
      - RestAPI
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref LambdaApprovalTemplateURL
      Parameters:
        RestAPI: !GetAtt RestAPI.Outputs.RestAPI
        Areyougoingtodeploytotestingsite: !Sub '${Areyougoingtodeploytotestingsite}'

#Lambda SendEmail Create
  LambdaSendEmail:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref LambdaSendEmailTemplateURL
      Parameters:
        supportmailaddress: !Sub '${supportmailaddress}'
        approvermailaddress: !Sub '${approvermailaddress}'
        Areyougoingtodeploytotestingsite: !Sub '${Areyougoingtodeploytotestingsite}'

#Lambda Account Create
  LambdaAccountCreation:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref LambdaAccountCreationTemplateURL
      Parameters:
        approvermailaddress: !Sub '${approvermailaddress}'
        supportmailaddress: !Sub '${supportmailaddress}'