AWSTemplateFormatVersion: 2010-09-09
Description: SES Create

Parameters:
  Email:
    Type: String


Resources:

#SES Create
  SES:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: !Sub '${Email}'

Outputs:
  SES:
    Value: !Ref SES
    Export:
      Name: SES