AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.

Parameters:
  approvermailaddress:
    Type: String

  supportmailaddress:
    Type: String

Resources:

#Lambda Create
  LambdaAccountCreationFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.8
      CodeUri: 's3://cf-templates-1vlqpgqefudg9-ap-northeast-1/CFn-Template/Human-Approval/Code/Account/LambdaAccountCreationFunction.zip'
      Description: ''
      MemorySize: 128
      Timeout: 30
      Role: !GetAtt  LambdaRole.Arn
      Environment:
        Variables:
          approver_mail_address: !Sub '${approvermailaddress}'
          support_mail_address: !Sub '${supportmailaddress}'
          customer_manual_url: >-
            https://ashisuto-aws-manual.s3.ap-northeast-1.amazonaws.com/aws_account_guide.pdf
          org_root_id: r-36rk
          org_unit_id: ou-36rk-3jz3j3oj
          spreadsheet_url: >-
            https://docs.google.com/spreadsheets/d/1wMhuPQmBR1ES6yhxdqyhX6FH0z5UR1-ql5SwZ1O4o7k/edit#gid=1485126580

#IAM Role Create
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - 'lambda.amazonaws.com'
            Action: 
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: AccountCreation-Dev-LambdaRolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'states:*'
                  - 'organizations:*'
                  - 'secretsmanager:*'
                  - 'ses:*'
                  - 'cloudwatch:*'
                  - 's3:*'
                  - 'logs:*'
                  - 'lambda:*'
                  - 'cloudformation:*'
                Resource: 
                  - '*'

Outputs:
  LambdaAccountCreation:
    Value: !GetAtt LambdaAccountCreationFunction.Arn
    Export:
      Name: LambdaAccountCreation