AWSTemplateFormatVersion: "2010-09-09"
Description:
 LodBalancer
Resources:
 MyLoadBalancer:
  Type: AWS::ElasticLoadBalancing::LoadBalancer
  Properties:
    AvailabilityZones:
    - "ap-northeast-1a"
    - "ap-northeast-1c"
    Instances:
    - Ref: logical name of AWS::EC2::i-07bc52133b1c633e7
    - Ref: logical name of AWS::EC2::i-0a876310ef7c135f4
    Listeners:
    - LoadBalancerPort: '80'
      InstancePort: '80'
      Protocol: HTTP
    - LoadBalancerPort: '443'
      InstancePort: '443'
      Protocol: HTTPS
    HealthCheck:
    - Target: HTTP:80/
      HealthyThreshold: '3'
      UnhealthyThreshold: '5'
      Interval: '30'
      Timeout: '5'
    