AWSTemplateFormatVersion: 2010-09-09
Description: Master stack

Parameters:
  Email:
    Type: String
    AllowedPattern: "^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$"
    ConstraintDescription: Must be a valid email address.

  RestAPITemplateURL:
    Type: String
    Default: https://cf-templates-1vlqpgqefudg9-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/CFn-Template/Human-Approval/reference-RestAPI.yml
  
  APIGatewayTemplateURL:
    Type: String
    Default: https://cf-templates-1vlqpgqefudg9-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/CFn-Template/Human-Approval/reference-APIGateway.yml

  SNSTemplateURL:
    Type: String
    Default: https://cf-templates-1vlqpgqefudg9-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/CFn-Template/Human-Approval/reference-SNS.yml

  StepFunctionTemplateURL:
    Type: String
    Default: https://cf-templates-1vlqpgqefudg9-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/CFn-Template/Human-Approval/reference-StepFunction.yml

  LambdaApprovalTemplateURL:
    Type: String
    Default: https://cf-templates-1vlqpgqefudg9-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/CFn-Template/Human-Approval/reference-LambdaApprovalFunction.yml

  LambdaSendEmailTemplateURL:
    Type: String
    Default: https://cf-templates-1vlqpgqefudg9-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/CFn-Template/Human-Approval/reference-LambdaHumanApprovalSendEmailFunction.yml

Resources:

#Rest API Create
  RestAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref RestAPITemplateURL

#API Gateway Create
  APIGateway:
    DependsOn:
      - LambdaApproval
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref APIGatewayTemplateURL
      Parameters:
        LambdaApprovalFunction: !GetAtt LambdaApproval.Outputs.LambdaApproval
        RestAPI: !GetAtt RestAPI.Outputs.RestAPI
        Resource: !GetAtt RestAPI.Outputs.Resource

#SNS Create
  SNS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref SNSTemplateURL
      Parameters:
        Email: !Sub '${Email}'

#Step Function Create
  StepFunction:
    DependsOn:
      - LambdaSendEmail
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref StepFunctionTemplateURL
      Parameters:
        Email: !Sub '${Email}'
        LambdaHumanApprovalSendEmailFunction: !GetAtt LambdaSendEmail.Outputs.LambdaSendEmail
        RestAPI: !GetAtt RestAPI.Outputs.RestAPI

#Lambda Create
  LambdaApproval:
    DependsOn:
      - RestAPI
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref LambdaApprovalTemplateURL
      Parameters:
        Email: !Sub '${Email}'
        RestAPI: !GetAtt RestAPI.Outputs.RestAPI

#Lambda Create
  LambdaSendEmail:
    DependsOn:
      - SNS
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref LambdaSendEmailTemplateURL
      Parameters:
        SNS: !GetAtt SNS.Outputs.SNS