AWSTemplateFormatVersion: 2010-09-09
Description: Rest API and Resource Create

Resources:

#Rest API Create
  RestAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: 'Human approval endpoint'
      Description: 'HTTP Endpoint backed by API Gateway and Lambda'
      FailOnWarnings: true

  #API Gateway Resource Create
  Resource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestAPI
      ParentId:  !GetAtt 'RestAPI.RootResourceId'
      PathPart: execution

Outputs:
  RestAPI:
    Value: !Ref RestAPI
    Export:
      Name: RestAPI

  Resource:
    Value: !Ref Resource
    Export:
      Name: Resource